[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"

[tool.dagster]
module_name = "google_drive_assets"
code_location_name = "google_drive_assets" 