ops:
  scrape_slack_content:
    config:
      max_messages_per_channel: 1000
      include_threads: true
      include_reactions: true
      include_files: true
      include_canvases: true
      include_links: true
      max_recursion_depth: 5 